apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: load-tester
  namespace: prod
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: load-tester
  chart:
    repository: https://flagger.app
    name: loadtester
    version: 0.18.0
  values:
    fullnameOverride: load-tester
